/* Generated by polc --emit-c-header from CExportApi. Do not edit.
 *
 * The methods below are declared `unknown <world>` in Polaron, which is what gives them a
 * bare linker symbol and a named calling convention. Everything else in the program has
 * internal linkage and a mangled name, and is deliberately not reachable from here.
 *
 * NOTE: `boolean` and `char` are 32-BIT in Polaron. They appear below as int32_t, and
 * declaring them as C's `bool` or `char` reads the wrong number of bytes.
 */
#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Api.polaron_add, c */
int32_t polaron_add(int32_t a, int32_t b);

/* Api.polaron_sum_squares, c */
int64_t polaron_sum_squares(int64_t n);

/* Api.polaron_is_even, c */
int32_t polaron_is_even(int32_t n);

#ifdef __cplusplus
}  /* extern "C" */
#endif
