// The other side of the boundary: a C++ program that calls into Polaron through the generated header.
//
// This is the first thing in the repository that verifies the OPEN world. The closed world -- Polaron
// calling Polaron across a .polb -- is checked by exact verification against the .polh fingerprint;
// the open world had a working export mechanism, no header for anyone to read, and nothing that ever
// tried it from the far side.
//
// The header is generated by `polc --emit-c-header` during the test, so a change to the mapping that
// makes it disagree with what codegen emits fails HERE, at a wrong answer, rather than in somebody's
// program months later.
#include <cstdint>
#include <cstdio>

#include "c_export_api.h"   // generated next to this file by the test harness

int main() {
    const int32_t sum = polaron_add(20, 22);
    const int64_t squares = polaron_sum_squares(100);
    // `boolean` is int32_t. Comparing against 0 rather than assigning to a `bool` is the point: a
    // narrowing store would hide exactly the bug this mapping exists to prevent.
    const int32_t even = polaron_is_even(7);
    const int32_t evenToo = polaron_is_even(8);

    std::printf("add=%d squares=%lld even7=%d even8=%d\n", sum,
                static_cast<long long>(squares), even, evenToo);
    return (sum == 42 && squares == 338350 && even == 0 && evenToo != 0) ? 0 : 1;
}
