#include "driver/build.h"
#include "driver/process.h"
#include "driver/toolchain.h"
#include "ldp3_region_core_src.h"  // generated by CMake from runtime/ldp3_region_core.hpp
#include <algorithm>
#include <cstdio>
#include <fstream>
#include <set>
#include <sstream>
#include <vector>

namespace ldp3::driver {
namespace fs = std::filesystem;
namespace {

Manifest readManifest(const fs::path& mf) {
    std::ifstream in(mf);
    std::stringstream ss;
    ss << in.rdbuf();
    return parseManifestText(ss.str());
}

// Map a manifest `target` to a clang/LLVM triple. The short forms are the ones a manifest uses; a value
// already containing a dash-separated triple (e.g. "x86_64-pc-windows-msvc") is passed through unchanged.
std::string targetTriple(const std::string& t) {
    if (t == "x86_64-windows" || t.empty()) return "x86_64-pc-windows-msvc";
    if (t == "aarch64-windows") return "aarch64-pc-windows-msvc";
    if (t == "x86_64-linux") return "x86_64-unknown-linux-gnu";
    if (t == "aarch64-linux") return "aarch64-unknown-linux-gnu";
    if (t == "x86_64-macos") return "x86_64-apple-darwin";
    if (t == "aarch64-macos") return "aarch64-apple-darwin";
    return t;  // already a full triple
}

// Collect the transitive closure of dependency bundles reachable from `direct`, walking each installed
// package's own manifest. Appends each package's .ldb to `out`. On a missing package, sets `missing`.
void collectClosure(const fs::path& packagesDir, const std::vector<std::string>& direct,
                    std::set<std::string>& visited, std::vector<fs::path>& out, std::string& missing) {
    for (const auto& name : direct) {
        if (!missing.empty()) return;
        if (visited.count(name)) continue;
        visited.insert(name);
        const fs::path pkgDir = packagesDir / name;
        const fs::path ldb = pkgDir / (name + ".ldb");
        if (!fs::is_regular_file(ldb)) { missing = name; return; }
        out.push_back(ldb);
        const fs::path mf = pkgDir / "ldp3.toml";
        if (fs::is_regular_file(mf)) {
            std::vector<std::string> children;
            for (const auto& d : readManifest(mf).dependencies) children.push_back(d.name);
            collectClosure(packagesDir, children, visited, out, missing);
        }
    }
}

// Collect every .ldp3 under the entry's directory (recursively) so a program can span multiple files.
// The entry is compiled first (it fixes the program name); the rest follow in a stable sorted order.
std::vector<fs::path> collectSources(const fs::path& entry) {
    std::vector<fs::path> extra;
    std::error_code ec;
    for (fs::recursive_directory_iterator it(entry.parent_path(), ec), end; it != end; it.increment(ec)) {
        if (ec) break;
        if (!it->is_regular_file() || it->path().extension() != ".ldp3") continue;
        if (fs::equivalent(it->path(), entry, ec)) continue;
        extra.push_back(it->path());
    }
    std::sort(extra.begin(), extra.end());
    std::vector<fs::path> all{entry};
    all.insert(all.end(), extra.begin(), extra.end());
    return all;
}

// Fold the (already-built) path dependencies of `m` into the link closure, transitively. Used after a
// dependency library has been built so a program links the code of its dependencies' dependencies too.
int collectPathClosure(const Manifest& m, const fs::path& projectDir, std::vector<fs::path>& closure,
                       std::set<fs::path>& seen) {
    for (const auto& d : m.dependencies) {
        if (d.path.empty()) continue;
        const fs::path depDir = fs::absolute(projectDir / d.path);
        const fs::path depMf = depDir / "ldp3.toml";
        if (!fs::is_regular_file(depMf)) continue;
        const Manifest dm = readManifest(depMf);
        const fs::path depLdb = depDir / dm.outputDir / (dm.name + ".ldb");
        if (seen.insert(depLdb).second) closure.push_back(depLdb);
        collectPathClosure(dm, depDir, closure, seen);
    }
    return 0;
}

// Build every path dependency of `m` and gather their bundles. `direct` receives this manifest's
// immediate path-dep .ldbs (passed to the compiler with --use for type-checking); `closure` receives
// the full transitive set (linked into the final program). A [library] path dependency is built the
// same way -- and buildProgram resolves that library's own path dependencies in turn -- so libraries
// can build on other libraries.
int buildPathDeps(const Manifest& m, const fs::path& projectDir, bool checkOnly,
                  std::vector<fs::path>& direct, std::vector<fs::path>& closure,
                  std::set<fs::path>& seen) {
    for (const auto& d : m.dependencies) {
        if (d.path.empty()) continue;  // registry dependencies come from packages/ (handled elsewhere)
        const fs::path depDir = fs::absolute(projectDir / d.path);
        const fs::path depMf = depDir / "ldp3.toml";
        if (!fs::is_regular_file(depMf)) {
            std::fprintf(stderr, "ldp3: path dependency '%s' has no ldp3.toml at %s\n",
                         d.name.c_str(), depDir.string().c_str());
            return 1;
        }
        const Manifest dm = readManifest(depMf);
        if (!dm.isLibrary) {
            std::fprintf(stderr, "ldp3: path dependency '%s' is not a [library]\n", d.name.c_str());
            return 1;
        }
        const fs::path depLdb = depDir / dm.outputDir / (dm.name + ".ldb");
        // A check runs on every pause in typing; reuse an existing bundle rather than rebuilding it.
        if (checkOnly) {
            if (fs::is_regular_file(depLdb)) direct.push_back(depLdb);
            continue;
        }
        std::printf("ldp3: building path dependency '%s'...\n", d.name.c_str());
        if (int rc = buildProgram(dm, depDir, BuildOptions{}); rc != 0) {
            std::fprintf(stderr, "ldp3: building path dependency '%s' failed\n", d.name.c_str());
            return rc;
        }
        direct.push_back(depLdb);
        if (seen.insert(depLdb).second) closure.push_back(depLdb);
        if (int rc = collectPathClosure(dm, depDir, closure, seen); rc != 0) return rc;
    }
    return 0;
}

}  // namespace

int buildProgram(const Manifest& m, const fs::path& projectDir, const BuildOptions& opts) {
    const Toolchain tc = locateToolchain();

    const fs::path entry = projectDir / m.entry;
    if (!fs::is_regular_file(entry)) {
        std::fprintf(stderr, "ldp3: entry file not found: %s\n", entry.string().c_str());
        return 1;
    }

    const fs::path outDir = projectDir / m.outputDir;
    std::error_code ec;
    fs::create_directories(outDir, ec);
    const fs::path ll = outDir / (m.name + ".ll");
    const fs::path exe = outDir / (m.name + exeSuffix());

    // A [library] project compiles to a distributable bundle (.ldb + .ldh) with no entry point, ready
    // to be consumed as a path dependency or installed into a packages/ directory.
    if (m.isLibrary) {
        const fs::path ldbOut = outDir / (m.name + ".ldb");
        // A library may itself depend on other libraries: build them and type-check against their .ldh.
        std::vector<fs::path> depDirect, depClosure;
        std::set<fs::path> depSeen;
        if (int rc = buildPathDeps(m, projectDir, opts.checkOnly, depDirect, depClosure, depSeen); rc != 0)
            return rc;
        std::vector<std::string> ca = {"--lib"};
        if (m.singleFile) ca.push_back(entry.string());
        else for (const auto& src : collectSources(entry)) ca.push_back(src.string());
        for (const auto& ldb : depDirect) {
            ca.push_back("--use");
            ca.push_back(ldb.string());
        }
        if (opts.checkOnly) {  // a library type-checks like a program, minus the entry point
            ca.insert(ca.begin(), "--check");
            for (const auto& ov : opts.overlays) {
                ca.push_back("--overlay");
                ca.push_back(ov);
            }
            const int rc = runProcess(tc.ldp3c, ca);
            return rc == -1 ? 1 : rc;
        }
        ca.push_back("-o");
        ca.push_back(ldbOut.string());
        ca.push_back("-O2");
        for (const auto& p : opts.passthrough) ca.push_back(p);
        if (int rc = runProcess(tc.ldp3c, ca); rc != 0) {
            std::fprintf(stderr, "ldp3: library compilation failed\n");
            return rc == -1 ? 1 : rc;
        }
        std::printf("wrote %s\n", ldbOut.string().c_str());
        return 0;
    }

    // Resolve dependency bundles. The consumer compiles against its *direct* dependencies only (a bundle's
    // .ldh already embeds its own transitive dependencies, so re-using them would redeclare types), but
    // links the *full transitive closure* of their code. Both the project's packages/ and, if declared, the
    // shared environment's packages/ contribute; a project may use both at once.
    std::vector<fs::path> directLdbs;  // for --use at compile time
    std::vector<fs::path> allLdbs;     // full closure, for linking
    {
        // Path dependencies (sibling [library] projects): build each, its own dependencies too, and
        // gather the transitive closure for linking.
        std::set<fs::path> pathSeen;
        if (int rc = buildPathDeps(m, projectDir, opts.checkOnly, directLdbs, allLdbs, pathSeen); rc != 0)
            return rc;
        // Registry dependencies (installed under packages/).
        std::set<std::string> visited;
        std::vector<std::string> direct;
        for (const auto& d : m.dependencies) {
            if (!d.path.empty()) continue;  // path deps handled above
            direct.push_back(d.name);
            directLdbs.push_back(projectDir / "packages" / d.name / (d.name + ".ldb"));
        }
        std::string missing;
        collectClosure(projectDir / "packages", direct, visited, allLdbs, missing);
        if (!missing.empty()) {
            std::fprintf(stderr, "ldp3: dependency '%s' is not installed; run 'ldp3 plug'\n", missing.c_str());
            return 1;
        }
    }
    if (!m.environment.empty()) {
        const fs::path envDir = ldp3HomeDir() / "environments" / m.environment;
        if (!fs::is_regular_file(envDir / "ldp3.toml")) {
            std::fprintf(stderr, "ldp3: environment '%s' does not exist; run 'ldp3 env new %s'\n",
                         m.environment.c_str(), m.environment.c_str());
            return 1;
        }
        std::set<std::string> visited;
        std::vector<std::string> direct;
        for (const auto& d : readManifest(envDir / "ldp3.toml").dependencies) {
            direct.push_back(d.name);
            directLdbs.push_back(envDir / "packages" / d.name / (d.name + ".ldb"));
        }
        std::string missing;
        collectClosure(envDir / "packages", direct, visited, allLdbs, missing);
        if (!missing.empty()) {
            std::fprintf(stderr, "ldp3: environment dependency '%s' is not installed; run 'ldp3 plug -e'\n",
                         missing.c_str());
            return 1;
        }
    }
    const std::vector<fs::path>& ldbs = allLdbs;  // extracted + linked below (the full closure)

    // Cross-compile plumbing (task #240): honor the manifest's target + sysroot. The default
    // "x86_64-windows" maps to the host Windows triple, so a normal build stays byte-identical; the target
    // and sysroot flow through the compile and link steps only for a non-default target, where the user
    // supplies the matching cross toolchain/libs.
    const std::string triple = targetTriple(m.target);
    const bool crossTarget = !m.target.empty() && m.target != "x86_64-windows";

    // THE FLOOR OF THE MACHINE A HOSTED BINARY IS ALLOWED TO ASSUME.
    //
    // clang's default x86_64 baseline is the original 2003 AMD64: SSE2, and nothing added since. That
    // default is not free and it is not theoretical. `Math.floor`, `ceil`, `round` and `trunc` have no
    // SSE2 instruction, so at the default baseline every one of them becomes a CALL INTO LIBM, register
    // spills included -- while one line of SSE4.1 does each of them. Measured in the inner loop of a game
    // built with this compiler: two floors cost 8.6 ns as calls, and are two instructions here.
    //
    // The language SHIPS those functions as builtins that lower to LLVM intrinsics, which reads as a
    // promise that they are instructions. At the old default they were not, on any program, ever.
    //
    // v2 COSTS THIS TARGET NOTHING. It means SSE4.1, SSE4.2 and POPCNT -- Nehalem, 2008 -- and Windows
    // 11, which is what this compiler builds for, refuses to install without SSE4.2 and POPCNT. There is
    // no machine that can run the operating system and not this.
    //
    // NOT v3 (AVX2, 2013), which WOULD exclude machines running Windows 11 today. Not freestanding
    // either: that path compiles -mgeneral-regs-only, with no vector unit at all, and returns above.
    const bool x86Host = triple.find("x86_64") != std::string::npos;
    const std::string baseline = "-march=x86-64-v2";

    // Freestanding (spec 36): there is no hosted runtime to link and no C entry, so compile to a
    // bare-metal object and stop. The user links that object with their own boot stub and linker script
    // (see kernel/ for a worked example). Dependencies are not supported in this mode yet.
    if (m.freestanding) {
        const std::string tt = m.fsTarget;   // [freestanding] target, default x86_64-unknown-none-elf
        // 1) LDP3 -> bare-metal LLVM IR. Like the hosted path, a program may span every src/**/*.ldp3
        //    (the entry first, the rest gathered), not just the entry file.
        std::vector<std::string> ca;
        if (m.singleFile) ca.push_back(entry.string());
        else for (const auto& src : collectSources(entry)) ca.push_back(src.string());
        ca.push_back("--target=" + tt);
        ca.push_back("-o");
        ca.push_back(ll.string());
        ca.push_back("-O2");
        for (const auto& p : opts.passthrough) ca.push_back(p);
        if (int rc = runProcess(tc.ldp3c, ca); rc != 0) {
            std::fprintf(stderr, "ldp3: compilation failed\n");
            return rc == -1 ? 1 : rc;
        }
        // 2) IR -> bare-metal object (no CRT, no EH/RTTI, no red zone, and NO SSE/MMX/x87).
        //
        // `-mgeneral-regs-only` is not a nicety. Without it LLVM vectorises ordinary integer loops into
        // `movdqa`/`por` on xmm registers -- a kernel image built here had 68 of them -- and an interrupt
        // handler is entered with no chance to save that state. The CPU pushes its frame and the handler's
        // own compiled code then uses the same xmm registers, so a value the interrupted computation was
        // holding is silently destroyed and execution continues with a wrong number in it.
        //
        // What that looks like from the outside is a machine that is subtly and rarely wrong: a readback
        // that answers false and then true a microsecond later from identical state, a loop whose bound
        // was clobbered running far past its trip count, a device that comes up broken and a different
        // one next boot. It moves whenever any code changes, because that changes which loops get
        // vectorised. It cannot be found by reading the failing code, because the failing code is
        // correct. It took a full session to corner in pico, and the thing that finally identified it
        // was that masking interrupts around the affected loop made it go away completely.
        //
        // Every real kernel does this -- Linux builds with -mno-sse -mno-mmx -mgeneral-regs-only for
        // exactly the same reason. A freestanding program has no OS underneath it to save vector state,
        // so the only safe amount to use is none. A kernel that WANTS SSE must enable it deliberately and
        // save it in its own entry paths; it must not arrive by accident from an optimiser decision.
        //
        // The red zone is NOT turned off here, and the missing flag is deliberate. `-mno-red-zone` is a
        // FRONT-END flag: clang honours it while lowering C or C++, by attaching a `noredzone` attribute
        // to each function it generates. The input on this line is a .ll, so the front end never runs,
        // the flag reaches nothing, and LLVM's x86 frame lowering consults only the attribute. It sat on
        // this command line for months doing nothing at all: the kernel it built had 1668 accesses below
        // RSP, and the assembly was byte-for-byte identical with the flag deleted. `-mgeneral-regs-only`
        // above is not the same case -- target features fall back to the subtarget, so it does apply,
        // and the two behaving differently side by side is exactly why this went unseen.
        //
        // ldp3c now marks the functions itself whenever the triple names no OS (see
        // CodeGenerator::applyBareMetalAttrs). That is the only place that can, and it is also the right
        // place: whether the code may use the red zone is a fact about the target it is generated for,
        // not about the command line that happens to consume the IR afterwards.
        const fs::path obj = outDir / (entry.stem().string() + ".o");
        if (int rc = runProcess(tc.clang, {"--target=" + tt, "-ffreestanding", "-fno-exceptions",
                                           "-fno-rtti", "-mgeneral-regs-only",
                                           "-c", ll.string(), "-o",
                                           obj.string()});
            rc != 0) {
            std::fprintf(stderr, "ldp3: bare-metal object compilation failed\n");
            return rc == -1 ? 1 : rc;
        }
        // Stop at the object only for the legacy shape: `[build] freestanding=true` with NO [freestanding]
        // section at all (the old workflow links by hand). A project that declares [freestanding] gets a
        // linked image -- with a generated linker script when it did not supply one.
        if (!m.hasFreestandingSection) {
            std::printf("wrote %s (freestanding object; add a [freestanding] section to link an image)\n",
                        obj.string().c_str());
            return 0;
        }
        // 3) Assemble each boot stub (.s) -> object (clang's integrated assembler, same triple).
        std::vector<std::string> linkObjs;
        // Minimal freestanding runtime: at -O2 LLVM's loop-idiom pass rewrites byte copy/zero loops into
        // memcpy/memset/memmove calls (the PE-section copy in a loader hits exactly this), which bare
        // metal must resolve. Provide them as weak symbols (a program may override) via a generated asm
        // stub, always linked. rep movsb/stosb -- itself immune to loop-idiom.
        // Also provide `__ldp3_panic`: LDP3's no-UB guards (division by zero, checked-arith overflow, an
        // out-of-bounds index, a full fixed region, an int that is not a value of its enum) lower to a
        // call to it, so a freestanding image that hits any guard must be able to link + terminate
        // deterministically instead of calling into nothing.
        //
        // The stub now PRINTS THE MESSAGE first, on COM1, and that is not a nicety. It used to be
        // `cli; hlt` and nothing else -- so `__ldp3_panic(const char*)` took a message and threw it
        // away, and every guard in the language reported itself, in a freestanding program, as a
        // machine that stopped. The guards are the whole claim that LDP3 has no undefined behaviour;
        // a guard whose report is discarded is indistinguishable from the corruption it prevented.
        //
        // Found by dogfooding: a kernel's PCI driver produced no output at all and looked like silent
        // memory corruption. It was this -- a region-full panic, correctly detected, correctly
        // trapped, and then unsayable. Debugging cost hours that a printed line would have cost none.
        //
        // COM1 at 0x3F8 is the choice because it is the one output an x86 freestanding target can
        // assume: no driver, no memory mapping, no console object, and it works before anything in the
        // program is initialised -- which is exactly when guards fire. The transmit-holding-register
        // poll is bounded by construction (`jnz` on a bit that a missing UART leaves clear reads back
        // 0xFF, so the loop exits), so a machine with no serial port still reaches the halt.
        //
        // Still `.weak`: a kernel with a real console overrides it and gets its own reporting. What
        // changed is the DEFAULT, so a program that never thought about it still gets told.
        {
            const fs::path rtS = outDir / "ldp3_fs_rt.s";
            const fs::path rtO = outDir / "ldp3_fs_rt.o";
            std::ofstream f(rtS);
            f << ".intel_syntax noprefix\n.section .text\n"
                 ".weak memcpy\nmemcpy:\n  mov rax, rdi\n  mov rcx, rdx\n  cld\n  rep movsb\n  ret\n"
                 ".weak memset\nmemset:\n  mov r8, rdi\n  mov rcx, rdx\n  mov al, sil\n  cld\n  rep stosb\n"
                 "  mov rax, r8\n  ret\n"
                 ".weak memmove\nmemmove:\n  mov rax, rdi\n  mov rcx, rdx\n  cmp rdi, rsi\n  jbe 1f\n"
                 "  lea rdi, [rdi+rcx-1]\n  lea rsi, [rsi+rcx-1]\n  std\n  rep movsb\n  cld\n  ret\n"
                 "1:\n  cld\n  rep movsb\n  ret\n"
                 // __ldp3_panic(const char* msg): "\r\nldp3 panic: " + msg + "\r\n" out of COM1, then
                 // halt forever with interrupts off. rdi = msg.
                 ".weak __ldp3_panic\n__ldp3_panic:\n"
                 "  cli\n"
                 "  mov rsi, rdi\n"                       // rsi = the caller's message
                 "  lea rdi, [rip + .Lldp3_panic_tag]\n"
                 "  call .Lldp3_puts\n"
                 "  mov rdi, rsi\n"
                 "  call .Lldp3_puts\n"
                 "  lea rdi, [rip + .Lldp3_panic_nl]\n"
                 "  call .Lldp3_puts\n"
                 "3:\n  hlt\n  jmp 3b\n"
                 // __ldp3_stack_mismatch(const char* method): what `--verify-stack` calls when a method
                 // returns on a different stack pointer than it was entered on. rdi = the method's name.
                 //
                 // Reports and CARRIES ON, unlike the panic above. That is the whole point: the fault it
                 // was built for happens about one boot in twenty and every attempt to stop the machine
                 // at it changed the timing enough to hide it. A line on the wire and an immediate
                 // return leaves the run intact, so the next thing that goes wrong is still observable
                 // and the two can be lined up.
                 ".weak __ldp3_stack_mismatch\n__ldp3_stack_mismatch:\n"
                 "  push rdi\n  push rsi\n  push rdx\n  push rax\n  push r8\n"
                 "  mov rsi, rdi\n"
                 "  lea rdi, [rip + .Lldp3_sp_tag]\n"
                 "  call .Lldp3_puts\n"
                 "  mov rdi, rsi\n"
                 "  call .Lldp3_puts\n"
                 "  lea rdi, [rip + .Lldp3_panic_nl]\n"
                 "  call .Lldp3_puts\n"
                 "  pop r8\n  pop rax\n  pop rdx\n  pop rsi\n  pop rdi\n"
                 "  ret\n"
                 // .Lldp3_puts(rdi = NUL-terminated bytes): one byte at a time out of 0x3F8, waiting
                 // for bit 5 of the line-status register (0x3FD) -- transmit holding register empty.
                 ".Lldp3_puts:\n"
                 "  mov al, [rdi]\n"
                 "  test al, al\n"
                 "  jz 5f\n"
                 "  mov r8b, al\n"
                 "4:\n"
                 "  mov dx, 0x3FD\n"
                 "  in al, dx\n"
                 "  test al, 0x20\n"
                 "  jz 4b\n"
                 "  mov dx, 0x3F8\n"
                 "  mov al, r8b\n"
                 "  out dx, al\n"
                 "  inc rdi\n"
                 "  jmp .Lldp3_puts\n"
                 "5:\n  ret\n"
                 ".section .rodata\n"
                 ".Lldp3_panic_tag: .asciz \"\\r\\nldp3 panic: \"\n"
                 ".Lldp3_panic_nl: .asciz \"\\r\\n\"\n"
                 ".Lldp3_sp_tag: .asciz \"\\r\\nldp3 STACK MISMATCH in \"\n"
                 ".section .text\n";
            f.close();
            if (int rc = runProcess(tc.clang, {"--target=" + tt, "-c", rtS.string(), "-o", rtO.string()});
                rc != 0) {
                std::fprintf(stderr, "ldp3: freestanding runtime (memcpy/memset/panic) failed to assemble\n");
                return rc == -1 ? 1 : rc;
            }
            linkObjs.push_back(rtO.string());
        }
        // `__ldp3_fail` bare metal: THE TWO NUMBERS.
        //
        // A guard that fires already says what broke, where, and in whose method -- freestanding has
        // carried all of that since the panic stub learned to print. What it could not carry was the
        // pair of values, because `__ldp3_panic` takes a finished string and a kernel has no stdio to
        // build one with. So `index = 9, length = 6` became `index out of bounds`, and the one line
        // that usually makes the mistake obvious on sight was the line a kernel did without --
        // in the code where a wrong index is least visible by other means.
        //
        // Fifty lines of C settle it: format the two integers into a static buffer and hand the whole
        // message to `__ldp3_panic`. Deliberately THROUGH the panic and not out of the serial port
        // directly, because `__ldp3_panic` is weak and a kernel with a real console overrides it. A
        // reporter that printed on its own would work perfectly here and silently drop the values in
        // every kernel that had taken the trouble to override -- which is the same defect again, one
        // layer up. One place to override, everything goes through it.
        //
        // Weak itself, for the same reason: a kernel that wants to add a stack trace, a register dump
        // or its own formatting replaces this and keeps the call shape.
        bool usesFailReporter = false;
        {
            std::ifstream irf(ll);
            for (std::string line; std::getline(irf, line);)
                if (line.find("__ldp3_fail") != std::string::npos) { usesFailReporter = true; break; }
        }
        if (usesFailReporter) {
            const fs::path fS = outDir / "ldp3_fs_fail.cpp";
            const fs::path fO = outDir / "ldp3_fs_fail.o";
            std::ofstream f(fS);
            // C++, and an OBJECT -- not C with a different extension. The buffer and how far it is
            // filled are one thing with one invariant ("never write past the end"), so they are a class
            // with the buffer private and the bound enforced in the one method that appends. Written as
            // free functions over a file-scope array, that invariant is restated at four call sites and
            // holds only as long as all four agree.
            f << "// generated by ldp3: freestanding failure reporter (the values a guard stopped on)\n"
                 "//\n"
                 "// The two names here are the ones the linker has to see, spelled by an asm label. This\n"
                 "// is C++, which would otherwise mangle them; the label renames the symbol and says\n"
                 "// nothing else about the declaration it sits on.\n"
                 "void __ldp3_panic(const char*) __asm__(\"__ldp3_panic\");\n"
                 "\n"
                 "// .bss, so it costs nothing in the image. Sized for a long path plus a long clause.\n"
                 "#ifndef LDP3_FS_FAIL_BUF\n"
                 "#define LDP3_FS_FAIL_BUF 1024\n"
                 "#endif\n"
                 "\n"
                 "namespace {\n"
                 "\n"
                 "// The message being composed. Everything is bounded and truncates rather than running\n"
                 "// off the end: a reporter that can itself corrupt memory is worse than no reporter.\n"
                 "class FailReport {\n"
                 "  public:\n"
                 "    void begin() { used_ = 0; }\n"
                 "\n"
                 "    void put(const char* s) {\n"
                 "        if (s == nullptr) return;\n"
                 "        while (*s != '\\0' && used_ + 1u < kCapacity) text_[used_++] = *s++;\n"
                 "    }\n"
                 "\n"
                 "    // Decimal, sign first. The negation is done in UNSIGNED so the most negative value\n"
                 "    // has somewhere to go -- negating it as a signed long long is the overflow this\n"
                 "    // very reporter exists to report.\n"
                 "    void put(long long v) {\n"
                 "        char digits[24];\n"
                 "        int n = 0;\n"
                 "        unsigned long long u = static_cast<unsigned long long>(v);\n"
                 "        if (v < 0) {\n"
                 "            u = 0ull - u;\n"
                 "            if (used_ + 1u < kCapacity) text_[used_++] = '-';\n"
                 "        }\n"
                 "        do {\n"
                 "            digits[n++] = static_cast<char>('0' + static_cast<int>(u % 10ull));\n"
                 "            u /= 10ull;\n"
                 "        } while (u != 0ull);\n"
                 "        while (n > 0 && used_ + 1u < kCapacity) text_[used_++] = digits[--n];\n"
                 "    }\n"
                 "\n"
                 "    // Terminate and hand the whole thing to the panic. THROUGH the panic, never to the\n"
                 "    // serial port directly: `__ldp3_panic` is weak and a kernel with a real console\n"
                 "    // overrides it, so a reporter that printed on its own would silently drop these\n"
                 "    // values in every kernel that had bothered to.\n"
                 "    void deliver() {\n"
                 "        text_[used_] = '\\0';\n"
                 "        __ldp3_panic(text_);\n"
                 "    }\n"
                 "\n"
                 "  private:\n"
                 "    static const unsigned kCapacity = LDP3_FS_FAIL_BUF;\n"
                 "    char text_[kCapacity];\n"
                 "    unsigned used_;\n"
                 "};\n"
                 "\n"
                 "FailReport g_report;\n"
                 "\n"
                 "}  // namespace\n"
                 "\n"
                 "// Weak, so a kernel that wants its own formatting -- a stack trace, a register dump --\n"
                 "// replaces this and keeps the call shape codegen emits.\n"
                 "__attribute__((weak))\n"
                 "void __ldp3_fail(const char* headline, const char* aLabel, long long a,\n"
                 "                 const char* bLabel, long long b, int code) __asm__(\"__ldp3_fail\");\n"
                 "\n"
                 "void __ldp3_fail(const char* headline, const char* aLabel, long long a,\n"
                 "                 const char* bLabel, long long b, int code) {\n"
                 "    (void)code;   // hosted exits with it; here there is nothing to exit to\n"
                 "    g_report.begin();\n"
                 "    g_report.put(headline);\n"
                 "    if (aLabel != nullptr && bLabel != nullptr) {\n"
                 "        g_report.put(\"   |  \");\n"
                 "        g_report.put(aLabel); g_report.put(\" = \"); g_report.put(a);\n"
                 "        g_report.put(\", \");\n"
                 "        g_report.put(bLabel); g_report.put(\" = \"); g_report.put(b);\n"
                 "    }\n"
                 "    g_report.deliver();\n"
                 "}\n";
            f.close();
            // The same bare-metal rules as every other generated source here: no red zone (an interrupt
            // lands on it) and no vector registers (nobody saves them). This one has a loop over bytes,
            // which is exactly the shape that acquires them by accident.
            //
            // And it is C++: `-fno-exceptions -fno-rtti` are what freestanding C++ needs and the whole
            // of what it needs. There is no personality routine and no type-info table to link against,
            // so nothing here reaches for a runtime -- the objects are plain data with methods, which
            // is the only kind a kernel can afford anyway.
            if (int rc = runProcess(tc.clang, {"--target=" + tt, "-ffreestanding", "-fno-builtin",
                                               "-fno-exceptions", "-fno-rtti",
                                               "-mno-red-zone", "-mgeneral-regs-only",
                                               "-c", fS.string(), "-o", fO.string()});
                rc != 0) {
                std::fprintf(stderr, "ldp3: freestanding failure reporter failed to compile\n");
                return rc == -1 ? 1 : rc;
            }
            linkObjs.push_back(fO.string());
        }
        // The persistent registry (spec 18.5). A persistent bound to a NAMED variable needs nothing at
        // all -- codegen gives it a private global -- which is why persistents work bare metal already,
        // whatever the guide says. The INDEXED form (`table[i] = new T()`) is the one that needs a
        // registry keyed by (array identity, slot), and without this it compiled clean and then failed
        // to link on a symbol the program never wrote.
        //
        // Deliberately NOT the hosted implementation. That one calloc/free/reallocs a growing table, so
        // it would drag the allocator into every freestanding image and make a kernel's memory use
        // depend on how many slots happened to be touched. A fixed table instead: no allocator, no
        // growth, no rehash, and running out is a panic that names the limit rather than a silent
        // corruption. A kernel wants a bound it can see.
        //
        // Emitted ONLY when the program actually calls it. The table and its arena are ~70 KiB of .bss,
        // and a program that never writes `table[i] = new T()` should not carry them -- a freestanding
        // image pays for what it uses. Read off the IR rather than guessed from the AST, so the test is
        // the same fact the linker will see.
        bool usesPersistRegistry = false;
        {
            std::ifstream irf(ll);
            for (std::string line; std::getline(irf, line);)
                if (line.find("__ldp3_persist_slot") != std::string::npos) { usesPersistRegistry = true; break; }
        }
        if (usesPersistRegistry) {
            const fs::path pS = outDir / "ldp3_fs_persist.cpp";
            const fs::path pO = outDir / "ldp3_fs_persist.o";
            std::ofstream f(pS);
            // C++, and the five parallel arrays became ONE object with five members. That is not a
            // stylistic preference: `g_key[j]`, `g_idx[j]`, `g_blk[j]`, `g_kb[j]` and `g_kn[j]` are
            // five halves of one entry, and every operation here had to keep all five in step by hand.
            // A slot that is written in four of the five is a registry entry that reads back as
            // something that was never stored, and nothing says so.
            f << "// generated by ldp3: freestanding persistent registry (spec 18.5)\n"
                 "//\n"
                 "// Every name the linker has to see is spelled by an asm label. This is C++, which\n"
                 "// would otherwise mangle them, and codegen calls these exact spellings; the label\n"
                 "// renames the symbol and says nothing else about the declaration it sits on.\n"
                 "using u64 = unsigned long long;\n"
                 "\n"
                 "void __ldp3_panic(const char*) __asm__(\"__ldp3_panic\");\n"
                 "void* __ldp3_persist_slot(const char* key, long long index, long long size)\n"
                 "    __asm__(\"__ldp3_persist_slot\");\n"
                 "void* __ldp3_persist_slot_keyed(const char* cls, const unsigned char* kb, long long kn,\n"
                 "                                long long size, const unsigned char* initial)\n"
                 "    __asm__(\"__ldp3_persist_slot_keyed\");\n"
                 "void __ldp3_persist_release_keyed(const char* cls, const unsigned char* kb, long long kn,\n"
                 "                                  long long size)\n"
                 "    __asm__(\"__ldp3_persist_release_keyed\");\n"
                 "void __ldp3_persist_release_all(const char* cls, long long off, long long width)\n"
                 "    __asm__(\"__ldp3_persist_release_all\");\n"
                 "\n"
                 "#ifndef LDP3_FS_PERSIST_SLOTS\n"
                 "#define LDP3_FS_PERSIST_SLOTS 256\n"
                 "#endif\n"
                 "// Blocks come from one static arena, so a persistent's address is stable for the whole\n"
                 "// run -- which is the entire point of a named persistent -- with no allocator behind it.\n"
                 "#ifndef LDP3_FS_PERSIST_ARENA\n"
                 "#define LDP3_FS_PERSIST_ARENA 65536\n"
                 "#endif\n"
                 "\n"
                 "// NOT YET AN OBJECT, and that is a stated debt rather than an oversight. These five\n"
                 "// arrays are five halves of one entry -- `g_key[j]`, `g_idx[j]`, `g_blk[j]`, `g_kb[j]`\n"
                 "// and `g_kn[j]` are updated together at every site, by hand, and a slot written in\n"
                 "// four of the five reads back as something that was never stored. They belong in one\n"
                 "// `Slot` with a `Registry` around it, the way the failure reporter beside this one is\n"
                 "// written. It compiles as C++ today; the refactor is the next step.\n"
                 "static const char* g_key[LDP3_FS_PERSIST_SLOTS];\n"
                 "static long long   g_idx[LDP3_FS_PERSIST_SLOTS];\n"
                 "static void*       g_blk[LDP3_FS_PERSIST_SLOTS];\n"
                 "static unsigned char* g_kb[LDP3_FS_PERSIST_SLOTS];  // owned key bytes, 0 = index form\n"
                 "static long long      g_kn[LDP3_FS_PERSIST_SLOTS];\n"
                 "static unsigned char g_arena[LDP3_FS_PERSIST_ARENA];\n"
                 "static u64 g_used = 0;\n"
                 "static int __ldp3_keyeq(const char* a, const char* b) {\n"
                 "    if (a == b) return 1;\n"
                 "    while (*a && *a == *b) { ++a; ++b; }\n"
                 "    return *a == *b;\n"
                 "}\n"
                 "void* __ldp3_persist_slot(const char* key, long long index, long long size) {\n"
                 "    u64 h = 1469598103934665603ULL;\n"
                 "    for (const char* p = key; *p; ++p) { h ^= (unsigned char)*p; h *= 1099511628211ULL; }\n"
                 "    h ^= (u64)index; h *= 1099511628211ULL;\n"
                 "    u64 j = h % (u64)LDP3_FS_PERSIST_SLOTS;\n"
                 "    for (u64 probes = 0; probes < (u64)LDP3_FS_PERSIST_SLOTS; ++probes) {\n"
                 "        if (g_key[j] == 0) break;\n"
                 "        if (g_idx[j] == index && __ldp3_keyeq(g_key[j], key)) return g_blk[j];\n"
                 "        j = (j + 1) % (u64)LDP3_FS_PERSIST_SLOTS;\n"
                 "    }\n"
                 "    if (g_key[j] != 0)\n"
                 "        __ldp3_panic(\"persistent registry full (raise LDP3_FS_PERSIST_SLOTS)\");\n"
                 "    u64 need = (u64)size; need = (need + 15u) & ~15ull;   // keep blocks 16-byte aligned\n"
                 "    if (g_used + need > (u64)LDP3_FS_PERSIST_ARENA)\n"
                 "        __ldp3_panic(\"persistent arena exhausted (raise LDP3_FS_PERSIST_ARENA)\");\n"
                 "    unsigned char* blk = &g_arena[g_used];\n"
                 "    for (u64 i = 0; i < (u64)size; ++i) blk[i] = 0;   // a fresh persistent starts zeroed\n"
                 "    g_used += need;\n"
                 "    g_key[j] = key; g_idx[j] = index; g_blk[j] = blk; g_kb[j] = 0; g_kn[j] = 0;\n"
                 "    return blk;\n"
                 "}\n"
                 "// Keyed persistents: the identity as serialised bytes, owned by the registry (see\n"
                 "// docs/design/persistent-keys.md). Bytes, not the object -- the registry outlives what\n"
                 "// supplied the key. The hash picks the bucket; the BYTES decide the match, so two\n"
                 "// identities that collide never merge.\n"
                 "static u64 __ldp3_pkey_hash(const char* cls, const unsigned char* kb, long long n) {\n"
                 "    u64 h = 1469598103934665603ULL;\n"
                 "    for (const char* p = cls; *p; ++p) { h ^= (unsigned char)*p; h *= 1099511628211ULL; }\n"
                 "    for (long long i = 0; i < n; ++i) { h ^= kb[i]; h *= 1099511628211ULL; }\n"
                 "    return h;\n"
                 "}\n"
                 "static int __ldp3_pmatch(u64 j, const char* cls, const unsigned char* kb, long long n) {\n"
                 "    if (g_kb[j] == 0 || g_kn[j] != n || !__ldp3_keyeq(g_key[j], cls)) return 0;\n"
                 "    for (long long i = 0; i < n; ++i) if (g_kb[j][i] != kb[i]) return 0;\n"
                 "    return 1;\n"
                 "}\n"
                 "void* __ldp3_persist_slot_keyed(const char* cls, const unsigned char* kb, long long kn,\n"
                 "                                long long size, const unsigned char* initial) {\n"
                 "    u64 j = __ldp3_pkey_hash(cls, kb, kn) % (u64)LDP3_FS_PERSIST_SLOTS;\n"
                 "    for (u64 p = 0; p < (u64)LDP3_FS_PERSIST_SLOTS; ++p) {\n"
                 "        if (g_key[j] == 0) break;\n"
                 "        if (__ldp3_pmatch(j, cls, kb, kn)) return g_blk[j];\n"
                 "        j = (j + 1) % (u64)LDP3_FS_PERSIST_SLOTS;\n"
                 "    }\n"
                 "    if (g_key[j] != 0)\n"
                 "        __ldp3_panic(\"persistent registry full (raise LDP3_FS_PERSIST_SLOTS)\");\n"
                 "    u64 need = ((u64)size + 15u) & ~15ull;\n"
                 "    u64 kneed = ((u64)kn + 15u) & ~15ull;   // the owned key copy lives in the arena too\n"
                 "    if (g_used + need + kneed > (u64)LDP3_FS_PERSIST_ARENA)\n"
                 "        __ldp3_panic(\"persistent arena exhausted (raise LDP3_FS_PERSIST_ARENA)\");\n"
                 "    unsigned char* blk = &g_arena[g_used]; g_used += need;\n"
                 "    unsigned char* own = &g_arena[g_used]; g_used += kneed;\n"
                 "    // A FIRST attach starts from what the constructor wrote; a reattach never gets\n"
                 "    // here and keeps what it accumulated.\n"
                 "    for (u64 i = 0; i < (u64)size; ++i) blk[i] = initial ? initial[i] : 0;\n"
                 "    for (long long i = 0; i < kn; ++i) own[i] = kb[i];\n"
                 "    g_key[j] = cls; g_idx[j] = 0; g_blk[j] = blk; g_kb[j] = own; g_kn[j] = kn;\n"
                 "    return blk;\n"
                 "}\n"
                 "// `release s.f;` -- zero what this identity accumulated. The entry stays, because a\n"
                 "// stable address across reattach is the point of a named persistent.\n"
                 "void __ldp3_persist_release_keyed(const char* cls, const unsigned char* kb, long long kn,\n"
                 "                                  long long size) {\n"
                 "    u64 j = __ldp3_pkey_hash(cls, kb, kn) % (u64)LDP3_FS_PERSIST_SLOTS;\n"
                 "    for (u64 p = 0; p < (u64)LDP3_FS_PERSIST_SLOTS; ++p) {\n"
                 "        if (g_key[j] == 0) return;\n"
                 "        if (__ldp3_pmatch(j, cls, kb, kn)) {\n"
                 "            for (long long i = 0; i < size; ++i) ((unsigned char*)g_blk[j])[i] = 0;\n"
                 "            return;\n"
                 "        }\n"
                 "        j = (j + 1) % (u64)LDP3_FS_PERSIST_SLOTS;\n"
                 "    }\n"
                 "}\n"
                 "// `release C.f all;` -- every identity the field ever had. ONE field, given as its byte\n"
                 "// offset and width: zeroing the whole block would discard the field's siblings too.\n"
                 "void __ldp3_persist_release_all(const char* cls, long long off, long long width) {\n"
                 "    for (u64 j = 0; j < (u64)LDP3_FS_PERSIST_SLOTS; ++j) {\n"
                 "        if (g_key[j] == 0 || g_kb[j] == 0) continue;\n"
                 "        if (__ldp3_keyeq(g_key[j], cls))\n"
                 "            for (long long i = 0; i < width; ++i)\n"
                 "                ((unsigned char*)g_blk[j])[off + i] = 0;\n"
                 "    }\n"
                 "}\n";
            f.close();
            // Same bare-metal rules as everything else in the image: no red zone (an interrupt lands on
            // it) and no vector registers (no one saves them). These are real sources, so unlike the .ll
            // above the flags do take effect here. Neither generates such code today -- measured, both
            // zero -- but they are compiled from strings a few hundred lines up, and the next person to
            // add a loop to one of them should not have to rediscover this.
            if (int rc = runProcess(tc.clang, {"--target=" + tt, "-ffreestanding", "-fno-builtin",
                                               "-fno-exceptions", "-fno-rtti",
                                               "-mno-red-zone", "-mgeneral-regs-only",
                                               "-c", pS.string(), "-o", pO.string()});
                rc != 0) {
                std::fprintf(stderr, "ldp3: freestanding persistent registry failed to compile\n");
                return rc == -1 ? 1 : rc;
            }
            linkObjs.push_back(pO.string());
        }

        // Regions in a freestanding program (spec 17). Codegen calls two runtime symbols to get and give
        // back a region's block; hosted builds find them in the managed runtime, and a bare-metal one had
        // NOTHING -- so `region r = itself.allocate(...)` compiled cleanly and failed at the link, which
        // meant the language's own ownership construct was unusable in exactly the code that needs
        // ownership most: kernels and freestanding programs.
        //
        // The backing is the project's `heap class`, reached through the same __ldp3_malloc/__ldp3_free
        // bridges `new` already uses. So a region here is arena-over-arena, which is what a region IS.
        // No block cache, unlike the hosted runtime: that cache exists to dodge an mmap round-trip per
        // acquire, and there is no mmap under this -- the heap class is the allocator itself.
        //
        // The flavored regions (pool/stack/fixedslot/ring), growable regions and every field region need
        // more than the block: a descriptor, free-lists, a destructor registry. That is real allocator
        // logic, and duplicating it here -- a bare-metal copy beside the hosted one in runtime/ -- would
        // give the language two region implementations that agree until the first fix lands in only one
        // of them. So the SAME source is compiled again for this target: runtime/ldp3_region_core.hpp,
        // embedded in this driver at build time, written out beside the object and compiled with static
        // pools behind it instead of libc.
        bool usesRegions = false;
        bool usesRegionDesc = false;
        bool needsCheckLive = false;
        {
            std::ifstream irf(ll);
            for (std::string line; std::getline(irf, line);) {
                if (line.find("__ldp3_region_acquire") != std::string::npos) usesRegions = true;
                // Every descriptor-bearing region initializes its header, whatever its flavor, so this one
                // symbol decides whether the core is needed -- read off the IR, which is the same fact the
                // linker will see. A program with only plain bump locals pays nothing for the core.
                if (line.find("__ldp3_region_init") != std::string::npos) usesRegionDesc = true;
                // A `declare` of the double-delete guard means the program deletes something and nothing
                // defined the guard -- which happens exactly when there is no `heap class` (with one,
                // codegen bridges it or emits a no-op). Programs got here as soon as a region could be
                // used without a heap class: `delete X from region R` then failed at the link.
                if (line.rfind("declare ", 0) == 0 &&
                    line.find("@__ldp3_check_live") != std::string::npos)
                    needsCheckLive = true;
            }
        }
        if (usesRegions || needsCheckLive) {
            const fs::path rS = outDir / "ldp3_fs_region.cpp";
            const fs::path rO = outDir / "ldp3_fs_region.o";
            // The region core travels with the object it backs: the same runtime/ldp3_region_core.hpp
            // the hosted runtime compiles, written out here and compiled again for this target. Even a
            // shim that needs only the layout constants includes it, so no magic number is ever spelled
            // twice.
            {
                std::ofstream core(outDir / "ldp3_region_core.hpp");
                core << ldp3::kRegionCoreSource;
            }
            std::ofstream f(rS);
            f << "// generated by ldp3: freestanding region backing (spec 17)\n"
                 "//\n"
                 "// A region's block comes from a STATIC ARENA, not from the project's `heap class`.\n"
                 "// That is the whole point: regions exist so nobody writes an arena by hand, and while\n"
                 "// their backing came from __ldp3_malloc every freestanding program that wanted a\n"
                 "// region had to write one anyway to satisfy it. A bare-metal program with regions and\n"
                 "// no heap class now links.\n"
                 "//\n"
                 "// Release is LIFO: a block returns to the arena only when it is the most recent one\n"
                 "// still out. Regions nest -- that is what a scope IS -- so the common case reclaims\n"
                 "// exactly; an out-of-order release keeps its bytes until the ones after it go. Stated\n"
                 "// rather than hidden, and it is the same bargain a stack makes.\n"
                 "\n"
                 "// HOW THE NAMES BELOW REACH THE LINKER. Codegen emits calls to `__ldp3_region_new` --\n"
                 "// that exact spelling -- and this is C++, which would otherwise mangle them. An asm\n"
                 "// label renames the symbol and says nothing else; a linkage specification would do the\n"
                 "// same job by borrowing C's rules for a declaration that has no reason to want them.\n"
                 "#define LDP3_ABI(name) __asm__(#name)\n"
                 "\n"
                 "// The methods marked with this stand exactly where a macro used to. A macro costs\n"
                 "// nothing at any optimization level and a call does not -- this object is built with\n"
                 "// none, and an empty profiler hook that became three calls on the allocation path is\n"
                 "// not the same code by any reading. So the compiler is told to fold them in.\n"
                 "#define LDP3_FOLD __attribute__((always_inline))\n"
                 "\n"
                 "using u64 = unsigned long long;\n"
                 "#include \"ldp3_region_core.hpp\"\n";
            if (usesRegions || usesRegionDesc)
              f << "\n"
                 "// A static bump arena that reclaims LIFO. This file needs two of them -- one for the\n"
                 "// region blocks, one for the destructor registries -- and they are the same arena with\n"
                 "// different bounds, so they are one class with two instances instead of two copies of\n"
                 "// the same fifteen lines that drift apart on the first fix applied to only one.\n"
                 "//\n"
                 "// Constant-initialized (the constructor is constexpr and both instances are built from\n"
                 "// address constants), so it lands ready in .data. Bare metal there is nobody to run a\n"
                 "// dynamic initializer, and an arena that came up with a null base would be found out\n"
                 "// on its first allocation.\n"
                 "class StaticArena {\n"
                 "  public:\n"
                 "    constexpr StaticArena(unsigned char* bytes, u64 capacity, const char* whenFull)\n"
                 "        : bytes_(bytes), capacity_(capacity), whenFull_(whenFull), used_(0) {}\n"
                 "\n"
                 "    // Panics rather than returning null: every caller here would have nothing to do\n"
                 "    // with a null but panic, and a kernel wants the reason rather than the pointer.\n"
                 "    unsigned char* take(u64 bytes) {\n"
                 "        const u64 need = round16(bytes);\n"
                 "        if (used_ + need > capacity_) __ldp3_panic(whenFull_);\n"
                 "        unsigned char* p = bytes_ + used_;\n"
                 "        used_ += need;\n"
                 "        return p;\n"
                 "    }\n"
                 "\n"
                 "    // Give a block back. Only the most recent one actually returns its bytes; anything\n"
                 "    // else keeps them until the blocks after it go.\n"
                 "    void giveBack(unsigned char* p, u64 bytes) {\n"
                 "        if (isTop(p, bytes)) used_ = static_cast<u64>(p - bytes_);\n"
                 "    }\n"
                 "\n"
                 "    // Resize a block: the top one grows where it stands, anything else is copied into\n"
                 "    // a fresh block (its old bytes are reclaimed when the blocks above it go).\n"
                 "    unsigned char* resize(unsigned char* p, u64 oldBytes, u64 newBytes) {\n"
                 "        if (isTop(p, oldBytes)) {\n"
                 "            used_ = static_cast<u64>(p - bytes_);\n"
                 "            return take(newBytes);   // same address, more of it\n"
                 "        }\n"
                 "        unsigned char* q = take(newBytes);\n"
                 "        if (p != nullptr)\n"
                 "            for (u64 i = 0; i < oldBytes; ++i) q[i] = p[i];\n"
                 "        return q;\n"
                 "    }\n"
                 "\n"
                 "  private:\n"
                 "    LDP3_FOLD bool isTop(const unsigned char* p, u64 bytes) const {\n"
                 "        return p != nullptr && p + round16(bytes) == bytes_ + used_;\n"
                 "    }\n"
                 "    LDP3_FOLD static constexpr u64 round16(u64 n) { return (n + 15u) & ~15ull; }\n"
                 "\n"
                 "    unsigned char* bytes_;\n"
                 "    u64 capacity_;\n"
                 "    const char* whenFull_;\n"
                 "    u64 used_;\n"
                 "};\n";
            if (usesRegions)
              f << "\n"
                 "#ifndef LDP3_FS_REGION_POOL\n"
                 "#define LDP3_FS_REGION_POOL 262144\n"
                 "#endif\n"
                 "static unsigned char g_regionBytes[LDP3_FS_REGION_POOL];\n"
                 "static StaticArena g_regionArena(g_regionBytes, LDP3_FS_REGION_POOL,\n"
                 "                                 \"region pool exhausted (raise LDP3_FS_REGION_POOL)\");\n"
                 "\n"
                 "// Each block carries its own size just below the pointer handed out, so release can\n"
                 "// tell whether it is the top one without the caller passing a length back.\n"
                 "void* __ldp3_region_acquire(u64 total) LDP3_ABI(__ldp3_region_acquire);\n"
                 "void* __ldp3_region_acquire(u64 total) {\n"
                 "    unsigned char* hdr = g_regionArena.take(total + 16);\n"
                 "    *reinterpret_cast<u64*>(hdr) = total;\n"
                 "    return hdr + 16;\n"
                 "}\n"
                 "\n"
                 "void __ldp3_region_release(void* block) LDP3_ABI(__ldp3_region_release);\n"
                 "void __ldp3_region_release(void* block) {\n"
                 "    if (block == nullptr) return;   // never allocated, or already released\n"
                 "    unsigned char* hdr = static_cast<unsigned char*>(block) - 16;\n"
                 "    g_regionArena.giveBack(hdr, *reinterpret_cast<u64*>(hdr) + 16);\n"
                 "}\n";
            if (usesRegionDesc) {
                // The destructor registry is metadata: it must not come out of the region's own declared
                // capacity, or a region would silently hold fewer objects than it was given room for.
                // Its own arena, then, with the same LIFO reclaim and the same named bound -- a kernel
                // wants a limit it can see rather than an allocator it cannot.
                f << "\n"
                     "// ---- the shared region core, backed by the arenas above ----\n"
                     "#ifndef LDP3_FS_REGION_META\n"
                     "#define LDP3_FS_REGION_META 32768\n"
                     "#endif\n"
                     "static unsigned char g_registryBytes[LDP3_FS_REGION_META];\n"
                     "static StaticArena g_registryArena(\n"
                     "    g_registryBytes, LDP3_FS_REGION_META,\n"
                     "    \"region destructor registry exhausted (raise LDP3_FS_REGION_META)\");\n"
                     "\n"
                     "// What the shared core is backed by here. A grown chain link is just another region\n"
                     "// block, so it comes from the same arena the region itself did.\n"
                     "class FreestandingRegionBacking {\n"
                     "  public:\n"
                     "    LDP3_FOLD static void* blockAlloc(u64 bytes) { return __ldp3_region_acquire(bytes); }\n"
                     "    LDP3_FOLD static void blockFree(void* p) { __ldp3_region_release(p); }\n"
                     "    LDP3_FOLD static void* metaAlloc(void* p, u64 oldBytes, u64 newBytes) {\n"
                     "        return g_registryArena.resize(static_cast<unsigned char*>(p), oldBytes, newBytes);\n"
                     "    }\n"
                     "    LDP3_FOLD static void metaFree(void* p, u64 bytes) {\n"
                     "        g_registryArena.giveBack(static_cast<unsigned char*>(p), bytes);\n"
                     "    }\n"
                     "    // No allocation profiler bare metal: there is no environment to switch one on with,\n"
                     "    // and these must cost what the empty macros they replaced cost -- nothing.\n"
                     "    LDP3_FOLD static void profileAlloc() {}\n"
                     "    LDP3_FOLD static void profileFree() {}\n"
                     "};\n"
                     "#define LDP3_REGION_BACKEND FreestandingRegionBacking\n"
                     "#define LDP3_REGION_CORE_IMPL\n"
                     "#include \"ldp3_region_core.hpp\"\n";
            }
            if (needsCheckLive) {
                // The no-UB double-delete guard, for a program with no `heap class` to bridge it from.
                // Bare metal it has exactly one thing to check: a region slot's stamp. There is no LDP3
                // heap pool under a freestanding program -- `new` goes to the user's heap class, whose
                // blocks carry no stamp of ours -- so a region object is the only block whose liveness
                // this can know, and it is also the only kind a heap-less program can be deleting.
                f << "\n"
                     "void __ldp3_check_live(void* ptr) LDP3_ABI(__ldp3_check_live);\n"
                     "void __ldp3_check_live(void* ptr) {\n"
                     "    if (ptr == nullptr) return;\n"
                     "    const Ldp3Hdr* h = reinterpret_cast<const Ldp3Hdr*>(\n"
                     "        static_cast<unsigned char*>(ptr) - 16);\n"
                     "    if (h->magic == LDP3_RFREED)\n"
                     "        __ldp3_panic(\"use of a freed object (double delete)\");\n"
                     "}\n";
            }
            f.close();
            // Bare-metal rules, as for the persistent registry above: no red zone, no vector registers.
            // C++ like everything else the driver emits -- it was the last generated file compiled as C,
            // and the header it shares with the hosted runtime went with it.
            if (int rc = runProcess(tc.clang, {"--target=" + tt, "-ffreestanding", "-fno-builtin",
                                               "-fno-exceptions", "-fno-rtti",
                                               "-mno-red-zone", "-mgeneral-regs-only",
                                               "-c", rS.string(), "-o", rO.string()});
                rc != 0) {
                std::fprintf(stderr, "ldp3: freestanding region backing failed to compile\n");
                return rc == -1 ? 1 : rc;
            }
            linkObjs.push_back(rO.string());
        }
        for (const std::string& b : m.bootSources) {
            const fs::path bo = outDir / (fs::path(b).stem().string() + ".o");
            if (int rc = runProcess(tc.clang,
                                    {"--target=" + tt, "-c", (projectDir / b).string(), "-o", bo.string()});
                rc != 0) {
                std::fprintf(stderr, "ldp3: boot stub '%s' failed to assemble\n", b.c_str());
                return rc == -1 ? 1 : rc;
            }
            linkObjs.push_back(bo.string());
        }
        linkObjs.push_back(obj.string());   // boot objects first so the boot entry (_start) leads
        // 4) Link into a bare-metal ELF image -- no CRT, no runtime. The linker script is GENERATED from
        // the manifest unless the project supplied one: a bare-metal layout is boilerplate (entry symbol,
        // load address, then the standard section order), so hand-writing it is the same busywork as
        // hand-writing the memcpy/memset stubs the driver already generates. `linker_script = "..."`
        // remains the escape hatch for a layout this template cannot express.
        fs::path script;
        if (!m.linkerScript.empty()) {
            script = projectDir / m.linkerScript;
        } else {
            script = outDir / (m.name + ".ld");
            std::ofstream ls(script);
            ls << "/* Generated by `ldp3 build` from [freestanding] in ldp3.toml -- do not edit.\n"
                  "   Override with `linker_script = \"...\"` if you need a layout this cannot express. */\n"
            // The entry symbol depends on whether this image boots a MACHINE or is loaded as a program.
            // A boot stub owns `_start` and hands over when the CPU is fit to run compiled code; without
            // one there is no `_start` at all, and naming it anyway is not a link error -- lld resolves a
            // missing ENTRY to address 0 and the image simply starts at null. That is how the shell came
            // out with e_entry = 0 and faulted on its first instruction with nothing on the serial line
            // to say why. So the symbol is chosen from what the image actually contains.
                  "ENTRY(" << (m.bootSources.empty() ? "kmain" : "_start")
               << ")\n\nSECTIONS {\n    . = " << m.loadAddress << ";\n\n";
            // The boot protocol decides what has to come FIRST: a loader scans the head of the image for
            // its handshake structure, so the section carrying it must lead.
            if (m.bootProtocol == "pvh") ls << "    .note.Xen : { *(.note.Xen) }\n\n";
            else if (m.bootProtocol == "multiboot2")  // GRUB scans the first 32 KiB for the header
                ls << "    .multiboot : { KEEP(*(.multiboot)) }\n\n";
            ls << "    .text   : { *(.text*) }\n"
                  "    .rodata : { *(.rodata*) }\n"
                  "    .data   : { *(.data*) }\n"
                  "    .bss    : { *(COMMON) *(.bss*) }\n}\n";
            if (!ls) {
                std::fprintf(stderr, "ldp3: could not write the generated linker script\n");
                return 1;
            }
        }
        const fs::path img = outDir / (m.name + ".elf");
        std::vector<std::string> la = {"-m", "elf_x86_64", "-T", script.string(),
                                       "--build-id=none", "-o", img.string()};
        for (const std::string& o : linkObjs) la.push_back(o);
        if (int rc = runProcess(tc.ldLld, la); rc != 0) {
            std::fprintf(stderr, "ldp3: freestanding link failed (ld.lld)\n");
            return rc == -1 ? 1 : rc;
        }
        std::printf("wrote %s (bare-metal image)\n", img.string().c_str());
        // 5) Optional image format on top of the linked ELF (spec 36): the ELF is always produced --
        // it is what a debugger, `qemu -kernel` and the PVH/multiboot loaders consume -- and these are
        // additional packagings of the same image.
        if (m.imageFormat == "bin") {
            // Flat binary: the loadable sections with no ELF wrapper, for a BIOS/UEFI stage, a ROM burn,
            // or an embedded target that jumps straight at the load address.
            const fs::path bin = outDir / (m.name + ".bin");
            if (int rc = runProcess(tc.objcopy, {"-O", "binary", img.string(), bin.string()}); rc != 0) {
                std::fprintf(stderr, "ldp3: could not flatten the image to a binary (llvm-objcopy)\n");
                return rc == -1 ? 1 : rc;
            }
            std::printf("wrote %s (flat binary)\n", bin.string().c_str());
        } else if (m.imageFormat == "iso") {
            // Bootable El Torito CD: a GRUB rescue tree with the kernel as a multiboot module. The kernel
            // must carry a multiboot2 header for GRUB to load it (`boot_protocol = "multiboot2"`).
            const fs::path root = outDir / "iso";
            const fs::path bootDir = root / "boot";
            const fs::path grubDir = bootDir / "grub";
            std::error_code ec;
            fs::create_directories(grubDir, ec);
            fs::copy_file(img, bootDir / (m.name + ".elf"), fs::copy_options::overwrite_existing, ec);
            {
                std::ofstream cfg(grubDir / "grub.cfg");
                cfg << "set timeout=0\nset default=0\n\nmenuentry \"" << m.name << "\" {\n"
                    << "    multiboot2 /boot/" << m.name << ".elf\n    boot\n}\n";
            }
            const fs::path iso = outDir / (m.name + ".iso");
            const int rc = runProcess(tc.xorriso, {"-as", "mkisofs", "-b",
                                                   "boot/grub/i386-pc/eltorito.img", "-no-emul-boot",
                                                   "-boot-load-size", "4", "-boot-info-table", "-o",
                                                   iso.string(), root.string()});
            if (rc != 0) {
                std::fprintf(stderr,
                             "ldp3: could not build the .iso -- xorriso is required (and a GRUB "
                             "i386-pc tree under %s). Install xorriso + grub-pc-bin, or set "
                             "$LDP3_XORRISO. The .elf above is complete and boots with `qemu -kernel`.\n",
                             grubDir.string().c_str());
                return rc == -1 ? 1 : rc;
            }
            std::printf("wrote %s (bootable ISO)\n", iso.string().c_str());
        } else if (m.imageFormat != "elf") {
            std::fprintf(stderr, "ldp3: unknown [freestanding] image = \"%s\" (expected elf, bin or iso)\n",
                         m.imageFormat.c_str());
            return 1;
        }
        return 0;
    }

    // 1) Compile: ldp3c <entry> [<other .ldp3>...] [--use <direct-dep.ldb>...] -o <ll> [passthrough].
    // A program may span several files under src/; the entry goes first, the rest follow.
    std::vector<std::string> compileArgs;
    if (m.singleFile) compileArgs.push_back(entry.string());
    else for (const auto& src : collectSources(entry)) compileArgs.push_back(src.string());
    for (const auto& ldb : directLdbs) {
        compileArgs.push_back("--use");
        compileArgs.push_back(ldb.string());
    }
    // A check answers with diagnostics, not an executable: same sources, same dependency headers, no
    // codegen and no link. Everything above this point (finding the sources, resolving the bundles) is the
    // reason it agrees with the build instead of approximating it.
    if (opts.checkOnly) {
        compileArgs.insert(compileArgs.begin(), "--check");
        for (const auto& ov : opts.overlays) {
            compileArgs.push_back("--overlay");
            compileArgs.push_back(ov);
        }
        const int rc = runProcess(tc.ldp3c, compileArgs);
        return rc == -1 ? 1 : rc;
    }
    compileArgs.push_back("-o");
    compileArgs.push_back(ll.string());
    // A debug build emits DWARF and skips ldp3c's middle-end so lines/variables survive; otherwise
    // optimize by default (a passthrough -O still overrides).
    compileArgs.push_back(opts.debug ? "-g" : "-O2");
    if (crossTarget) compileArgs.push_back("--target=" + triple);  // codegen for the requested target
    for (const auto& p : opts.passthrough) compileArgs.push_back(p);
    if (int rc = runProcess(tc.ldp3c, compileArgs); rc != 0) {
        std::fprintf(stderr, "ldp3: compilation failed\n");
        return rc == -1 ? 1 : rc;
    }

    // 2) Extract each dependency's bitcode and compile it to a native object. (Handing raw bitcode to the
    // linker alongside the MSVC-built runtime lib pushes lld-link into an LTO path that drops the CRT
    // imports; a plain object sidesteps that.)
    std::vector<std::string> depObjects;
    for (const auto& ldb : ldbs) {
        const fs::path bc = outDir / (ldb.stem().string() + ".bc");
        if (int rc = runProcess(tc.ldp3c, {"--extract-code", ldb.string(), "-o", bc.string()}); rc != 0) {
            std::fprintf(stderr, "ldp3: extracting code from '%s' failed\n", ldb.string().c_str());
            return rc == -1 ? 1 : rc;
        }
        const fs::path obj = outDir / (ldb.stem().string() + ".obj");
        std::vector<std::string> depCompile = {"-O2", "-Wno-override-module"};
        if (x86Host) depCompile.push_back(baseline);
        depCompile.push_back("-c");
        depCompile.push_back(bc.string());
        depCompile.push_back("-o");
        depCompile.push_back(obj.string());
        if (int rc = runProcess(tc.clang, depCompile); rc != 0) {
            std::fprintf(stderr, "ldp3: compiling dependency object from '%s' failed\n", ldb.string().c_str());
            return rc == -1 ? 1 : rc;
        }
        depObjects.push_back(obj.string());
    }

    // 3) Link. A self-contained bundle (tc.libDir set) compiles the IR to an object and links it with
    // lld-link against its own CRT/import libs, needing no system Visual Studio or Windows SDK -- LDP3
    // runs on a bare Windows 10/11 x64 machine. Otherwise clang drives the link against the system SDK.
    if (!tc.libDir.empty()) {
        const fs::path mainObj = outDir / (ll.stem().string() + ".main.obj");
        std::vector<std::string> mainCompile = {"--target=" + triple};
        if (!m.sysroot.empty()) mainCompile.push_back("--sysroot=" + m.sysroot);
        if (opts.debug) { mainCompile.push_back("-g"); mainCompile.push_back("-O0"); }
        else mainCompile.push_back("-O2");
        if (x86Host) mainCompile.push_back(baseline);
        mainCompile.push_back("-Wno-override-module");
        mainCompile.push_back("-c");
        mainCompile.push_back(ll.string());
        mainCompile.push_back("-o");
        mainCompile.push_back(mainObj.string());
        if (int rc = runProcess(tc.clang, mainCompile); rc != 0) {
            std::fprintf(stderr, "ldp3: compiling to object failed\n");
            return rc == -1 ? 1 : rc;
        }
        std::vector<std::string> linkArgs = {"-out:" + exe.string(), "-nologo", "-defaultlib:libcmt",
                                             "-defaultlib:oldnames", "-libpath:" + tc.libDir,
                                             mainObj.string()};
        for (const auto& obj : depObjects) linkArgs.push_back(obj);
        linkArgs.push_back(tc.runtimeLib);
        linkArgs.push_back("legacy_stdio_definitions.lib");
        linkArgs.push_back("ws2_32.lib");
        for (const auto& lib : m.nativeLibs)  // FFI: system libs the program links against (opengl32, ...)
            linkArgs.push_back(lib + ".lib");
        // A GUI program (subsystem = "windows") links without a console window. The program still enters
        // through `main`, so keep the C entry point (WINDOWS default would look for WinMain).
        if (m.subsystem == "windows") {
            linkArgs.push_back("-subsystem:windows");
            linkArgs.push_back("-entry:mainCRTStartup");
        }
        if (int rc = runProcess(tc.lldLink, linkArgs); rc != 0) {
            std::fprintf(stderr, "ldp3: link failed\n");
            return rc == -1 ? 1 : rc;
        }
    } else {
        std::vector<std::string> linkArgs;
        if (crossTarget) linkArgs.push_back("--target=" + triple);  // cross-compile (task #240)
        if (!m.sysroot.empty()) linkArgs.push_back("--sysroot=" + m.sysroot);
        if (opts.debug) { linkArgs.push_back("-g"); linkArgs.push_back("-O0"); }
        else linkArgs.push_back("-O2");
        if (x86Host) linkArgs.push_back(baseline);   // this path compiles the .ll as well as links it
#ifdef _WIN32
        // Force lld as the linker so the choice is deterministic -- a native object input can otherwise
        // flip clang to the MSVC link.exe, which does not pull in the UCRT the runtime needs.
        linkArgs.push_back("-fuse-ld=lld");
#endif
        linkArgs.push_back("-Wno-override-module");
        linkArgs.push_back(ll.string());
        for (const auto& obj : depObjects) linkArgs.push_back(obj);
        linkArgs.push_back(tc.runtimeLib);
#ifdef _WIN32
        linkArgs.push_back("-llegacy_stdio_definitions");  // UCRT printf/scanf as real symbols
        linkArgs.push_back("-lws2_32");                    // Winsock, used by the runtime's net layer
#else
        linkArgs.push_back("-lpthread");  // Thread/async runtime
        linkArgs.push_back("-ldl");       // dl_iterate_phdr, used by reimport
        linkArgs.push_back("-lm");        // libm for the math builtins
        linkArgs.push_back("-lstdc++");   // Itanium EH runtime (__cxa_*, personality, _ZTIPv)
        linkArgs.push_back("-rdynamic");  // export symbols so a dlopened bundle resolves them
#endif
        for (const auto& lib : m.nativeLibs)  // FFI: system libs the program links against (opengl32, ...)
            linkArgs.push_back("-l" + lib);
#ifdef _WIN32
        // A GUI program (subsystem = "windows") links without a console window; keep `main` as the entry.
        if (m.subsystem == "windows") {
            linkArgs.push_back("-Wl,-subsystem:windows");
            linkArgs.push_back("-Wl,-entry:mainCRTStartup");
        }
#endif
        linkArgs.push_back("-o");
        linkArgs.push_back(exe.string());
        if (int rc = runProcess(tc.clang, linkArgs); rc != 0) {
            std::fprintf(stderr, "ldp3: link failed\n");
            return rc == -1 ? 1 : rc;
        }
    }
    std::printf("wrote %s\n", exe.string().c_str());

    // 4) Optionally run.
    if (opts.run) return runProcess(exe.string(), opts.runArgs);
    return 0;
}

}  // namespace ldp3::driver
