#include "driver/lockfile.h"
#include <fstream>

namespace polaron::driver {
namespace {

std::string trim(const std::string& s) {
    const char* ws = " \t\r\n";
    const auto b = s.find_first_not_of(ws);
    if (b == std::string::npos) {
        return "";
    }
    const auto e = s.find_last_not_of(ws);
    return s.substr(b, e - b + 1);
}

std::string unquote(const std::string& s) {
    if (s.size() >= 2 && s.front() == '"' && s.back() == '"') {
        return s.substr(1, s.size() - 2);
    }
    return s;
}

}  // namespace

LockMap readLock(const std::filesystem::path& path) {
    LockMap out;
    std::ifstream in(path);
    if (!in) {
        return out;
    }
    std::string line;
    bool inLocked = false;
    while (std::getline(in, line)) {
        const std::string s = trim(line);
        if (s.empty() || s[0] == '#') {
            continue;
        }
        if (s.front() == '[' && s.back() == ']') { inLocked = (s == "[locked]"); continue; }
        if (!inLocked) {
            continue;
        }
        const auto eq = s.find('=');
        if (eq == std::string::npos) {
            continue;
        }
        out[trim(s.substr(0, eq))] = unquote(trim(s.substr(eq + 1)));
    }
    return out;
}

bool writeLock(const std::filesystem::path& path, const LockMap& locked) {
    std::ofstream out(path, std::ios::binary);
    if (!out) {
        return false;
    }
    out << "# Generated by polaron plug. Records the exact resolved source of every installed package.\n";
    out << "[locked]\n";
    for (const auto& [name, source] : locked) {
        out << name << " = \"" << source << "\"\n";
    }
    return static_cast<bool>(out);
}

}  // namespace polaron::driver
